<a href="https://colab.research.google.com/github/Anuragsingh007-bit/Natural-language-processing/blob/main/NLP_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [ ]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<nothing>")


In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [ ]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [ ]:
tokenizer.document_count

11

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [ ]:
from keras.utils import pad_sequences

nsequences = pad_sequences(sequences,maxlen = 10, padding = 'post')
nsequences

array([[ 7,  2,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9, 10,  4,  0,  0,  0,  0,  0,  0,  0],
       [11, 12, 13, 14,  0,  0,  0,  0,  0,  0],
       [15, 16,  0,  0,  0,  0,  0,  0,  0,  0],
       [17,  4, 18,  5,  6,  0,  0,  0,  0,  0],
       [19, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [21, 22,  0,  0,  0,  0,  0,  0,  0,  0],
       [23, 24,  2,  3,  0,  0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

# Sentiment Analysis using RNN

In [ ]:
from keras.datasets import imdb
imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [ ]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [ ]:
print(len(X_train[0]))
print(len(X_train[2]))

218
141


In [ ]:
print(y_train[7])
print(y_train[0])

0
1


In [ ]:
from keras.utils import pad_sequences
maxlen = 500

X_train = pad_sequences(X_train,maxlen = maxlen, padding = 'post')
X_test = pad_sequences(X_test,maxlen = maxlen, padding = 'post')

In [ ]:
X_train[0]

array([    1,    14,    22,    16,    43,   530,   973,  1622,  1385,
          65,   458,  4468,    66,  3941,     4,   173,    36,   256,
           5,    25,   100,    43,   838,   112,    50,   670, 22665,
           9,    35,   480,   284,     5,   150,     4,   172,   112,
         167, 21631,   336,   385,    39,     4,   172,  4536,  1111,
          17,   546,    38,    13,   447,     4,   192,    50,    16,
           6,   147,  2025,    19,    14,    22,     4,  1920,  4613,
         469,     4,    22,    71,    87,    12,    16,    43,   530,
          38,    76,    15,    13,  1247,     4,    22,    17,   515,
          17,    12,    16,   626,    18, 19193,     5,    62,   386,
          12,     8,   316,     8,   106,     5,     4,  2223,  5244,
          16,   480,    66,  3785,    33,     4,   130,    12,    16,
          38,   619,     5,    25,   124,    51,    36,   135,    48,
          25,  1415,    33,     6,    22,    12,   215,    28,    77,
          52,     5,

In [ ]:
print(len(X_train[0]))
print(len(X_train[2]))

500
500


# model Architecture

In [ ]:
model = Sequential()
model.add(SimpleRNN(32, input_shape = (500,1), return_sequences= False))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(metrics = ['accuracy'], optimizer = 'adam', loss = 'binary_crossentropy')

In [ ]:
# model Training
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 77s 95ms/step - accuracy: 0.4987 - loss: 0.6946 - val_accuracy: 0.5018 - val_loss: 0.6945
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 74s 95ms/step - accuracy: 0.5110 - loss: 0.6936 - val_accuracy: 0.5050 - val_loss: 0.6932
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 82s 95ms/step - accuracy: 0.5008 - loss: 0.6939 - val_accuracy: 0.5028 - val_loss: 0.6943
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 75s 96ms/step - accuracy: 0.5069 - loss: 0.6933 - val_accuracy: 0.5068 - val_loss: 0.6932
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 81s 95ms/step - accuracy: 0.5071 - loss: 0.6934 - val_accuracy: 0.5027 - val_loss: 0.6947


In [ ]:
# model.save('path.h5')
# model.save('path.pkl')   #pickle

# model.load('')

model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step


array([[0.44275185],
       [0.44275185],
       [0.5510986 ],
       ...,
       [0.44275185],
       [0.44275185],
       [0.44275185]], dtype=float32)



```
# This is formatted as code
```

embedding layers using Keras


In [ ]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [ ]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<nothing>")

In [ ]:
tokenizer.fit_on_texts(docs)
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding = 'post')
sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

model arcitecture
#

In [ ]:
from keras import Sequential
from keras.layers import Dense , SimpleRNN ,Embedding
model.Sequential()
model.add(Embedding(23, output_dim = 2 , input_length = 500))
model.add(SimpleRNN(32,input_shape=(500,1) , return_sequences = False))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

AttributeError: 'Sequential' object has no attribute 'Sequential'

In [ ]:


from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding

# Initialize the model properly
model = Sequential()

# Add layers
model.add(Embedding(input_dim=23, output_dim=2, input_length=500))
model.add(SimpleRNN(32, return_sequences=False))  # input_shape not needed here; handled by Embedding
model.add(Dense(1, activation='sigmoid'))

# Show summary
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# embedding and RNN on IMDB dataset

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN ,Embedding ,Flatten
from keras.utils import pad_sequences

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

In [ ]:
# Data processing # step 1 visualization of the data
# zero padding

X_train = pad_sequences(X_train, padding = 'post',maxlen = 500)
X_test = pad_sequences(X_test, padding = 'post',maxlen = 500)

In [ ]:
X_train.shape

(25000, 500)

In [ ]:
print(len(X_train[0]))
print(len(X_train[2]))

500
500


In [ ]:
print(len(X_train))
print(len(X_train))

25000
25000


In [ ]:
# model arcitecture
model = Sequential()
model.add(Embedding(input_dim = 10000 , output_dim = 2, input_length = 500))
model.add(SimpleRNN(32 , return_sequences=False))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# model architecture
model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# model compile
model.compile(metrics = ['acc'], optimizer = 'adam', loss = 'binary_crossentropy')

In [ ]:
# model train
# model Training
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 94s 118ms/step - acc: 0.4938 - loss: 0.6947 - val_acc: 0.4968 - val_loss: 0.6946
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 135s 108ms/step - acc: 0.4991 - loss: 0.6945 - val_acc: 0.5033 - val_loss: 0.6932
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 86s 110ms/step - acc: 0.5065 - loss: 0.6940 - val_acc: 0.5019 - val_loss: 0.6935
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 147s 117ms/step - acc: 0.5060 - loss: 0.6943 - val_acc: 0.4988 - val_loss: 0.6942
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 85s 108ms/step - acc: 0.5087 - loss: 0.6930 - val_acc: 0.5005 - val_loss: 0.6934


In [78]:
# model train
# model Training
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 72s 91ms/step - accuracy: 0.5081 - loss: 0.6940 - val_accuracy: 0.5040 - val_loss: 0.6931
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 87s 98ms/step - accuracy: 0.5102 - loss: 0.6933 - val_accuracy: 0.5032 - val_loss: 0.6937
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 77s 91ms/step - accuracy: 0.4978 - loss: 0.6937 - val_accuracy: 0.5060 - val_loss: 0.6945
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 75s 96ms/step - accuracy: 0.4982 - loss: 0.6941 - val_accuracy: 0.4992 - val_loss: 0.6942
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 79s 91ms/step - accuracy: 0.5000 - loss: 0.6939 - val_accuracy: 0.5056 - val_loss: 0.6935


In [82]:
# Prediction
X_test[0][0:50]

array([    1,   591,   202,    14,    31,     6,   717,    10,    10,
       18142, 10698,     5,     4,   360,     7,     4,   177,  5760,
         394,   354,     4,   123,     9,  1035,  1035,  1035,    10,
          10,    13,    92,   124,    89,   488,  7944,   100,    28,
        1668,    14,    31,    23,    27,  7479,    29,   220,   468,
           8,   124,    14,   286,   170], dtype=int32)

In [83]:
test_data = X_test[0][0:50]

In [84]:
test_data

array([    1,   591,   202,    14,    31,     6,   717,    10,    10,
       18142, 10698,     5,     4,   360,     7,     4,   177,  5760,
         394,   354,     4,   123,     9,  1035,  1035,  1035,    10,
          10,    13,    92,   124,    89,   488,  7944,   100,    28,
        1668,    14,    31,    23,    27,  7479,    29,   220,   468,
           8,   124,    14,   286,   170], dtype=int32)

In [85]:
test_data = X_test[0][0:50].reshape(1,-1)

In [86]:
if model.predict(test_data) < 0.5:
  print('negative review')
else:
  print('positive review')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step
positive review
